---
# Configures a PostgreSQL server instance with WebApps conventions

- name: create privileged postgresql roles linked to operating system users for web apps users
  postgresql_user:
               name="{{ item }}"
           password="password"
    role_attr_flags=SUPERUSER,CREATEROLE,CREATEDB,REPLICATION
              state=present
  with_items: "{{ web_application_team_usernames }}"
  become_user: postgres
