---
# Installs htop process viewer on non-production environments

- name: install htop - CentOS
  yum:
             pkg={{ item }}
    update_cache=yes
           state=present
  with_items:
  - htop
  when: ansible_distribution == "CentOS"

- name: install htop - Ubuntu
  apt:
                 pkg={{ item }}
        update_cache=yes
    cache_valid_time=3600
               state=present
  with_items:
    - htop
  when: ansible_distribution == "Ubuntu"
