---
# Installs/configures common/useful utilities

- include: utilities-htop.yml
  when: ansible_local.bas_systems_inventory.system_instance.environment != "production"


- include: utilities-nano.yml
  when: ansible_local.bas_systems_inventory.system_instance.environment != "production"
